config/routes.rb
Rails.application.routes.draw do
  get '/' => "home#top"

  get 'items' => "items#index"
  get 'items/part/:part_number' => "items#part"
  get 'items/date/:supplier_reply' => "items#date"
  get 'items/work/:work_number' => "items#work"
  get 'parts/edit/:part_number' => "parts#index"
  get 'parts/destroy/:part_number' => "parts#destroy"
  get 'items/rescheduled' => "items#rescheduled"
  get 'items/weld' => "items#weld"
  get 'items/tig' => "items#tig"
  get 'items/add' => "items#add"
  get 'items/bend' => "items#bend"
  get 'items/laser' => "items#laser"
  get 'items/valve' => "items#valve"
  get 'items/ebw' => "items#ebw"
  get 'items/long' => "items#long"
  get 'items/out' => "items#out"
  get 'parts' => "parts#index"

  post 'part_search' => "items#part_search"
  post 'work_search' => "items#work_search"
  post 'parts/register' => "parts#register"
  post 'parts' => "parts#index"
  post 'items/laser/request/create/:id' => "items#laser_request_create"
  post 'items/laser/request/cancel/:id' => "items#laser_request_cancel"
  post 'items/laser/receive/create/:id' => "items#laser_receive_create"
  post 'items/laser/receive/cancel/:id' => "items#laser_receive_cancel"

  get 'items/index'
  resources :items do
    collection do
      post :import
    end
  end

  
end

app/models/item.rb
class Item < ApplicationRecord
  require 'active_support/core_ext/object/try'

  def point(item)
    part = Part.find_by(part_number: item[:part_number])

    return 0 unless part
    part.half + part.thr_eth + part.qtr + part.eth
  end

  def half?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.half > 0

    false
  end

  def eth?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.eth > 0

    false
  end

  def tig?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.tig == true
    
    false
  end

  def add?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.add == true
    
    false
  end

  def bend?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.bend == true
    
    false
  end

  def laser?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.laser == true
    
    false
  end

  def valve?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.valve == true
    
    false
  end

  def ebw?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.ebw == true
    
    false
  end

  def long?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.long == true
    
    false
  end

  def out?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if item[:out] == true
    return true if part.out == true
    
    false
  end

  def add_remarks(item)
    text = ""

    text += "1/2″溶接あり/ " if half?(item) && !out?(item)
    text += "1/8″溶接あり/ " if eth?(item) && !out?(item)
    text += "Tigあり/ " if tig?(item)
    text += "追加工あり/ " if add?(item) && !out?(item)
    text += "曲げあり/ " if bend?(item) && point(item) != 0 && !out?(item)
    text += "曲げのみ/ " if bend?(item) && point(item) == 0 && !out?(item)
    text += "レーザー/ " if laser?(item) && !out?(item)
    text += "バルブ/ " if valve?(item)
    text += "EBW/ " if ebw?(item)
    text += "長尺/ " if long?(item)
    text += "外注/ " if out?(item) && !ebw?(item) && !long?(item)

    text.slice!(-2, 1)
    
    text.to_s
  end

  def self.import(file)
    xlsx = Roo::Excelx.new(file.tempfile)

    ord = xlsx.row(2).index("Order Nr") + 1
    itm = xlsx.row(2).index("Item") + 1
    par = xlsx.row(2).index("Material") + 1
    qty = xlsx.row(2).index {|v| v == "Qty" || v == "QTY"} + 1
    sup = xlsx.row(2).index("Supplier Reply") + 1
    wor = sup + 2
    rem = wor + 2

    xlsx.each_row_streaming(offset: 2, pad_cells: true) do |row|
      next unless row[ord]

      item = self.new(
        order_number: row[ord].value,
        item_number: row[itm].value,
        part_number: row[par].value.to_s.sub(/Rev.*/m, "").strip,
        qty: row[qty].value,
        supplier_reply: row[sup].value,
        work_number: row[wor].value.to_s.delete("^0-9").slice(0, 5),
        remarks: row[rem].value.to_s
      )

      next unless item.supplier_reply

      if $bloom.any? {|i| item.remarks.include?(i)}
        item.out = true
      else
        item.out = nil
      end

      item.note = item.add_remarks(item) + item.remarks
      
      if item.out?(item)
        item.points = 0
      else
        item.points = item.point(item) * item.qty
      end

      item_exist = Item.find_by(order_number: item.order_number, item_number: item.item_number)

      if item_exist
        item_exist.part_number = item.part_number
        item_exist.qty = item.qty
        item_exist.ex_reply = item_exist.supplier_reply
        item_exist.supplier_reply = item.supplier_reply
        item_exist.out = item.out
        item_exist.note = item.note
        item_exist.points = item.points

        if item_exist.supplier_reply < item_exist.ex_reply
          item_exist.status = "Pull in"
        elsif item_exist.supplier_reply > item_exist.ex_reply
          item_exist.status = "Push out"
        else
          item_exist.status = "Remain"
        end

        item_exist.save

      else
        item.status = "New"
        item.save
      end
    end
    
    past_items = Item.where('supplier_reply < ?', Date.current)
    
    past_items.each do |past|
      past.status = "Remain"
      past.save
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.where('supplier_reply > ?', Date.current).order(:supplier_reply).order(:order_number).order(:item_number)
    @part_numbers = Part.all.pluck(:part_number)
  end

  def import
    Item.import(params[:file])
    redirect_to("/")
  end

  def rescheduled
    @items = Item.where('supplier_reply > ?', Date.current).where(status: "Pull in").or(Item.where(status: "Push out")).order(:ex_reply).order(:supplier_reply).order(:order_number).order(:item_number)
    @part_numbers = Part.all.pluck(:part_number)
  end

  def date
    @items = Item.where(supplier_reply: params[:supplier_reply]).order(:supplier_reply).order(:order_number).order(:item_number)
    @supplier_reply = params[:supplier_reply].to_date
    @part_numbers = Part.all.pluck(:part_number)
  end

  def part
    @items = Item.where(part_number: params[:part_number]).where('supplier_reply > ?', Date.current).order(:supplier_reply).order(:order_number).order(:item_number)
    @part = Part.find_by(part_number: params[:part_number])
    @part_number = params[:part_number]
  end

  def work
    @items = Item.where(work_number: params[:work_number]).order(:item_number)
    @work_number = params[:work_number]
    @part_numbers = Part.all.pluck(:part_number)
  end

  def weld
    @items = Item.where('supplier_reply > ?', Date.current).where('points != ?', 0).order(:supplier_reply).order(:order_number).order(:item_number)
    @part_numbers = Part.all.pluck(:part_number)
  end

  def tig
    @part_numbers = Part.where(tig: true, out: nil).pluck(:part_number)
    @items = Item.where(part_number: @part_numbers).where('supplier_reply > ?', Date.current).order(:supplier_reply).order(:order_number).order(:item_number)
  end

  def add
    @part_numbers = Part.where(add: true, out: nil).pluck(:part_number)
    @items = Item.where(part_number: @part_numbers).where(out: nil).where('supplier_reply > ?', Date.current).order(:supplier_reply).order(:order_number).order(:item_number)
  end

  def bend
    @part_numbers = Part.where(bend: true, out: nil, laser: nil).pluck(:part_number)
    @items = Item.where(part_number: @part_numbers).where(out: nil).where('supplier_reply > ?', Date.current).order(:supplier_reply).order(:order_number).order(:item_number)
  end

  def laser
    @part_numbers = Part.where(laser: true,out: nil).pluck(:part_number)
    @items = Item.where(part_number: @part_numbers).where(out: nil).where('supplier_reply > ?', Date.current).order(:supplier_reply).order(:order_number).order(:item_number)
  end

  def valve
    @part_numbers = Part.where(valve: true, out: nil).pluck(:part_number)
    @items = Item.where(part_number: @part_numbers).where(out: nil).where('supplier_reply > ?', Date.current).order(:supplier_reply).order(:order_number).order(:item_number)
  end

  def ebw
    @part_numbers = Part.where(ebw: true).pluck(:part_number)
    @items = Item.where(part_number: @part_numbers).where('supplier_reply > ?', Date.current).order(:supplier_reply).order(:order_number).order(:item_number)
  end

  def long
    @part_numbers = Part.where(long: true).pluck(:part_number)
    @items = Item.where(part_number: @part_numbers).where('supplier_reply > ?', Date.current).order(:supplier_reply).order(:order_number).order(:item_number)
  end

  def out
    @part_numbers = Part.where(out: true, ebw: nil, long: nil).pluck(:part_number)
    @items = Item.where(part_number: @part_numbers).or(Item.where(out: true)).where('supplier_reply > ?', Date.current).order(:supplier_reply).order(:order_number).order(:item_number)
  end

  def laser_request_create
    @item = Item.find_by(id: params[:id])
    @item.las_req = true
    @item.save
  end

  def laser_request_cancel
    @item = Item.find_by(id: params[:id])
    @item.las_req = nil
    @item.save
  end

  def laser_receive_create
    @item = Item.find_by(id: params[:id])
    @item.las_rec = true
    @item.save
  end

  def laser_receive_cancel
    @item = Item.find_by(id: params[:id])
    @item.las_rec = nil
    @item.save
  end

  def part_search
    @parts = Part.where('part_number like ?',"%#{params[:part]}%").order(:part_number)
  end

  def work_search
    work = params[:work]
    redirect_to ("/items/work/#{work}")
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def points(item)
    part = Part.find_by(part_number: item[:part_number])

    return 0 unless part
    return part.half + part.thr_eth + part.qtr + part.eth
  end

  def tig?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.tig == true
    
    false
  end

  def add?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.add == true
    
    false
  end

  def bend?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.bend == true
    
    false
  end

  def laser?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.laser == true
    
    false
  end

  def valve?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.valve == true
    
    false
  end

  def ebw?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.ebw == true
    
    false
  end

  def long?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if part.long == true
    
    false
  end

  def out?(item)
    part = Part.find_by(part_number: item[:part_number])

    return false unless part
    return true if item[:out] == true
    return true if part.out == true
    
    false
  end

  def remarks(item)
    text = ""

    text += "Tigあり/ " if tig?(item)
    text += "追加工あり/ " if add?(item) && !out?(item)
    text += "曲げあり/ " if bend?(item) && points(item) != 0 && !out?(item)
    text += "曲げのみ/ " if bend?(item) && points(item) == 0 && !out?(item)
    text += "レーザー/ " if laser?(item) && !out?(item)
    text += "バルブ/ " if valve?(item)
    text += "EBW/ " if ebw?(item)
    text += "長尺/ " if long?(item)
    text += "外注/ " if out?(item) && !ebw?(item) && !long?(item)

    text.slice!(-2, 1)
    
    return text.to_s
  end
end

app/views/items/bend.html.erb
<h1>曲げ</h1>
<div class="main_table">
  <% qty_total = 0 %>
  <% i = 0 %>
  <% while i < @items.length do %>
    <table>
      <thead>
        <tr>
          <th>Order number</th>
          <th>Item</th>
          <th>Part number</th>
          <th>Qty</th>
          <th class="status">Status</th>
          <th>前回回答</th>
          <th>Supplier reply</th>
          <th>工番</th>
          <th class="right part">備考</th>
        </tr>
      </thead>

      <tbody>
        <% loop { %>
          <% qty_total += @items[i][:qty] %>

          <tr>
            <td><%= @items[i][:order_number] %></td>
            <td><%= @items[i][:item_number] %></td>
            <td><%= link_to(@items[i][:part_number], "/items/part/#{@items[i][:part_number]}") %></td>
            <td><%= @items[i][:qty] %></td>
            <% if @items[i][:status] == "Pull in" %>
              <td class="pull_in">
            <% elsif @items[i][:status] == "Push out" %>
              <td class="push_out">
            <% elsif @items[i][:status] == "New" %>
              <td class="new">
            <% else %>
              <td class="remain">
            <% end %>
            <%= @items[i][:status] %>
            </td>
            <td class="ex_reply"><% if @items[i][:ex_reply] %><%= @items[i][:ex_reply].strftime('%Y/%m/%d') %><% end %></td>
            <td><%= link_to(@items[i][:supplier_reply].strftime('%Y/%m/%d'), "/items/date/#{@items[i][:supplier_reply]}") %></td>
            <td><%= link_to(@items[i][:work_number], "/items/work/#{@items[i][:work_number]}") %></td>
            <td class="right"><% if points(@items[i]) != 0 %>溶接あり<% else %>曲げのみ<% end %></td>
          </tr>

          <% if @items[i + 1] && @items[i][:supplier_reply] != @items[i + 1][:supplier_reply] || !@items[i + 1] %>
            <% i += 1 %>
            <% break %>
          <% end %>

          <% i += 1 %>
        <% } %>
      </tbody>
    
      <tfoot>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td class="total"><%= qty_total %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <% qty_total = 0 %>
      </tfoot>
    </table>
  <% end %>
</div>

app/views/items/date.html.erb
<h1><%= @supplier_reply.strftime('%Y/%m/%d') %></h1>

<table class="sorttbl" id="myTable">
  <thead>
    <tr>
      <th>Order number</th>
      <th>Item</th>
      <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child(3)')">Part number <i class="fa fa-sort-down"></th>
      <th>Qty</th>
      <th class="status">Status</th>
      <th>前回回答</th>
      <th>Supplier reply</th>
      <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child(2)'), w3.sortHTML('#myTable','.item', 'td:nth-child(8)')">工番 <i class="fa fa-sort-down"></th>
      <th class="note">備考</th>
      <th class="right">溶接数</th>
    </tr>
  </thead>

  <tbody>
  <% qty_total = 0 %>
  <% points_total = 0 %>

    <% @items.each do |item| %>
      <tr class="item">
        <% qty_total += item.qty %>

        <% unless out?(item) %>
          <% points_total += points(item) * item.qty %>
        <% end %>

        <td><%= item.order_number %></td>
        <td><%= item.item_number %></td>
        <% if @part_numbers.include?(item.part_number) %>
          <td>
        <% else %>
          <td class="unregisted">
        <% end %>
            <%= link_to(item.part_number, "/items/part/#{item.part_number}") %></td>
        <td><%= item.qty %></td>
        <% if item.status == "Pull in" %>
              <td class="pull_in">
            <% elsif item.status == "Push out" %>
              <td class="push_out">
            <% elsif item.status == "New" %>
              <td class="new">
            <% else %>
              <td class="remain">
            <% end %>
            <%= item.status %>
            </td>
            <td class="ex_reply"><% if item.ex_reply %><%= item.ex_reply.strftime('%Y/%m/%d') %><% end %></td>
        <td><%= link_to(item.supplier_reply.strftime('%Y/%m/%d'), "/items/date/#{item.supplier_reply}") %></td>
        <td><%= link_to(item.work_number, "/items/work/#{item.work_number}") %></td>
        <td><%= item.note %></td>
        <td class="right">
          <% if out?(item) || points(item) == 0 %>
            -
          <% else %>
            <%= points(item) * item.qty %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
  <tfoot>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td class="total"><%= qty_total %></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td class="total"><%= points_total %></td>
    </tr>
  </tfoot>
</table>

app/views/items/ebw.html.erb
<h1>EBW</h1>
<div class="main_table">
  <% qty_total = 0 %>
  <% i = 0 %>
  <% while i < @items.length do %>
    <table>
      <thead>
        <tr>
          <th>Order number</th>
          <th>Item</th>
          <th>Part number</th>
          <th>Qty</th>
          <th class="status">Status</th>
          <th>前回回答</th>
          <th>Supplier reply</th>
          <th class="right">工番</th>
        </tr>
      </thead>

      <tbody>
        <% loop { %>
          <% qty_total += @items[i][:qty] %>

          <tr>
            <td><%= @items[i][:order_number] %></td>
            <td><%= @items[i][:item_number] %></td>
            <td><%= link_to(@items[i][:part_number], "/items/part/#{@items[i][:part_number]}") %></td>
            <td><%= @items[i][:qty] %></td>
            <% if @items[i][:status] == "Pull in" %>
              <td class="pull_in">
            <% elsif @items[i][:status] == "Push out" %>
              <td class="push_out">
            <% elsif @items[i][:status] == "New" %>
              <td class="new">
            <% else %>
              <td class="remain">
            <% end %>
            <%= @items[i][:status] %>
            </td>
            <td class="ex_reply"><% if @items[i][:ex_reply] %><%= @items[i][:ex_reply].strftime('%Y/%m/%d') %><% end %></td>
            <td><%= link_to(@items[i][:supplier_reply].strftime('%Y/%m/%d'), "/items/date/#{@items[i][:supplier_reply]}") %></td>
            <td class="right"><%= link_to(@items[i][:work_number], "/items/work/#{@items[i][:work_number]}") %></td>
          </tr>

          <% if @items[i + 1] && @items[i][:supplier_reply] != @items[i + 1][:supplier_reply] || !@items[i + 1] %>
            <% i += 1 %>
            <% break %>
          <% end %>

          <% i += 1 %>
        <% } %>
      </tbody>
    
      <tfoot>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td class="total"><%= qty_total %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <% qty_total = 0 %>
      </tfoot>
    </table>
  <% end %>
</div>

app/views/items/index.html.erb
<h1>All</h1>
<div class="import">
  <%= form_with url: import_items_path, local: true do |form| %>
    <%= form.file_field :file %>
    <%= form.submit "更新" %>
  <% end %>
<%= form_tag("/part_search") do %>
    <input name="part"  autocomplete="off">
    <input type="submit" value="図番検索">
  <% end %>
  <%= form_tag("/work_search") do %>
    <input name="work"  autocomplete="off">
    <input type="submit" value="工番検索">
  <% end %>
</div>

<div>
  <% qty_total = 0 %>
  <% points_total = 0 %>
  <% i = 0 %>
  <% while i < @items.length do %>
    <table>
      <thead>
        <tr>
          <th>Order number</th>
          <th>Item</th>
          <th class="part">Part number</th>
          <th>Qty</th>
          <th class="status">Status</th>
          <th>前回回答</th>
          <th>Supplier reply</th>
          <th>工番</th>
          <th class="note">備考</th>
          <th class="right">溶接数</th>
        </tr>
      </thead>

      <tbody>
        <% loop { %>
          <% qty_total += @items[i][:qty] %>
          <% points_total += @items[i][:points] %>
          
          <tr>
            <td><%= @items[i][:order_number] %></td>
            <td><%= @items[i][:item_number] %></td>
            <% if @part_numbers.include?(@items[i][:part_number]) %>
              <td>
            <% else %>
              <td class="unregisted">
            <% end %>
            <%= link_to(@items[i][:part_number], "/items/part/#{@items[i][:part_number]}") %></td>
            <td><%= @items[i][:qty] %></td>
            <% if @items[i][:status] == "Pull in" %>
              <td class="pull_in">
            <% elsif @items[i][:status] == "Push out" %>
              <td class="push_out">
            <% elsif @items[i][:status] == "New" %>
              <td class="new">
            <% else %>
              <td class="remain">
            <% end %>
            <%= @items[i][:status] %>
            </td>
            <td class="ex_reply"><% if @items[i][:ex_reply] %><%= @items[i][:ex_reply].strftime('%Y/%m/%d') %><% end %></td>
            <td><%= link_to(@items[i][:supplier_reply].strftime('%Y/%m/%d'), "/items/date/#{@items[i][:supplier_reply]}") %></td>
            <td><%= link_to(@items[i][:work_number], "/items/work/#{@items[i][:work_number]}") %></td>
            <td><%= @items[i][:note] %></td>
            <td class="right">
              <% if @items[i][:points] == 0 %>
                -
              <% else %>
               <%= @items[i][:points] %>
              <% end %>
            </td>
          </tr>

          <% if @items[i + 1] && @items[i][:supplier_reply] != @items[i + 1][:supplier_reply] || !@items[i + 1] %>
            <% i += 1 %>
            <% break %>
          <% end %>

          <% i += 1 %>
        <% } %>
      </tbody>
    
      <tfoot>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td class="total"><%= qty_total %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td class="total"><%= points_total %></td>
        </tr>
        <% qty_total = 0 %>
        <% points_total = 0 %>
      </tfoot>
    </table>
  <% end %>
</div>

app/views/items/laser_receive_cancel.js.erb
$('#laser_receive_<%= @item.id %>').html("<%= j(render "items/laser_receive", item: @item) %>");

app/views/items/laser_request_cancel.js.erb
$('#laser_request_<%= @item.id %>').html("<%= j(render "items/laser_request", item: @item) %>");

app/views/items/laser_request_create.js.erb
$('#laser_request_<%= @item.id %>').html("<%= j(render "items/laser_request", item: @item) %>");

app/views/items/out.html.erb
<h1>外注</h1>
<div class="main_table">
  <% qty_total = 0 %>
  <% i = 0 %>
  <% while i < @items.length do %>
    <table>
      <thead>
        <tr>
          <th>Order number</th>
          <th>Item</th>
          <th>Part number</th>
          <th>Qty</th>
          <th class="status">Status</th>
          <th>前回回答</th>
          <th>Supplier reply</th>
          <th>工番</th>
          <th class="right note">備考</th>
        </tr>
      </thead>

      <tbody>
        <% loop { %>
          <% qty_total += @items[i][:qty] %>

          <tr>
            <td><%= @items[i][:order_number] %></td>
            <td><%= @items[i][:item_number] %></td>
            <td><%= link_to(@items[i][:part_number], "/items/part/#{@items[i][:part_number]}") %></td>
            <td><%= @items[i][:qty] %></td>
            <% if @items[i][:status] == "Pull in" %>
              <td class="pull_in">
            <% elsif @items[i][:status] == "Push out" %>
              <td class="push_out">
            <% elsif @items[i][:status] == "New" %>
              <td class="new">
            <% else %>
              <td class="remain">
            <% end %>
            <%= @items[i][:status] %>
            </td>
            <td class="ex_reply"><% if @items[i][:ex_reply] %><%= @items[i][:ex_reply].strftime('%Y/%m/%d') %><% end %></td>
            <td><%= link_to(@items[i][:supplier_reply].strftime('%Y/%m/%d'), "/items/date/#{@items[i][:supplier_reply]}") %></td>
            <td><%= link_to(@items[i][:work_number], "/items/work/#{@items[i][:work_number]}") %></td>
            <td class="right"><%= @items[i][:note] %></td>
          </tr>

          <% if @items[i + 1] && @items[i][:supplier_reply] != @items[i + 1][:supplier_reply] || !@items[i + 1] %>
            <% i += 1 %>
            <% break %>
          <% end %>

          <% i += 1 %>
        <% } %>
      </tbody>
    
      <tfoot>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td class="total"><%= qty_total %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <% qty_total = 0 %>
      </tfoot>
    </table>
  <% end %>
</div>

app/views/items/tig.html.erb
<h1>Tig</h1>
<div class="main_table">
  <% qty_total = 0 %>
  <% i = 0 %>
  <% while i < @items.length do %>
    <table>
      <thead>
        <tr>
          <th>Order number</th>
          <th>Item</th>
          <th class="part">Part number</th>
          <th>Qty</th>
          <th class="status">Status</th>
          <th>前回回答</th>
          <th>Supplier reply</th>
          <th class="right">工番</th>
        </tr>
      </thead>

      <tbody>
        <% loop { %>
          <% qty_total += @items[i][:qty] %>

          <tr>
            <td><%= @items[i][:order_number] %></td>
            <td><%= @items[i][:item_number] %></td>
            <td><%= link_to(@items[i][:part_number], "/items/part/#{@items[i][:part_number]}") %></td>
            <td><%= @items[i][:qty] %></td>
            <% if @items[i][:status] == "Pull in" %>
              <td class="pull_in">
            <% elsif @items[i][:status] == "Push out" %>
              <td class="push_out">
            <% elsif @items[i][:status] == "New" %>
              <td class="new">
            <% else %>
              <td class="remain">
            <% end %>
            <%= @items[i][:status] %>
            </td>
            <td class="ex_reply"><% if @items[i][:ex_reply] %><%= @items[i][:ex_reply].strftime('%Y/%m/%d') %><% end %></td>
            <td><%= link_to(@items[i][:supplier_reply].strftime('%Y/%m/%d'), "/items/date/#{@items[i][:supplier_reply]}") %></td>
            <td class="right"><%= link_to(@items[i][:work_number], "/items/work/#{@items[i][:work_number]}") %></td>
          </tr>

          <% if @items[i + 1] && @items[i][:supplier_reply] != @items[i + 1][:supplier_reply] || !@items[i + 1] %>
            <% i += 1 %>
            <% break %>
          <% end %>

          <% i += 1 %>
        <% } %>
      </tbody>
    
      <tfoot>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td class="total"><%= qty_total %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <% qty_total = 0 %>
      </tfoot>
    </table>
  <% end %>
</div>